### ISSUE TITLE
Joining game 

### ISSUE THREAD

**Issue by jaylac2000** [ArchonKlaus/GTA#1]
when you join the game the plugin is in another language. ITs greate for the banking system. But is there a way to make it english?

**Comment by samupozzo** [comment]
Actually no. Today I will make it English, now is in Italian.

**Comment by jaylac2000** [comment]
thank u .i tried to do it my self but im not a coder so it was a hardcore fail what i did lol

**Comment by samupozzo** [comment]
Updated the plugin to version v1.3. Now it is in English.

**Comment by jaylac2000** [comment]
thank u so much!
